# Generated by Django 4.1.7 on 2023-02-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='media/hotel/')),
                ('address', models.CharField(max_length=255)),
                ('stars', models.CharField(max_length=255)),
                ('breakfast', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('departure', models.CharField(blank=True, max_length=100)),
                ('arrival', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule', models.FileField(blank=True, null=True, upload_to='')),
                ('availability', models.IntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/packet/')),
                ('title', models.CharField(max_length=250)),
                ('day_1', models.TextField(blank=True, null=True)),
                ('day_2', models.TextField(blank=True, null=True)),
                ('day_3', models.TextField(blank=True, null=True)),
                ('day_4', models.TextField(blank=True, null=True)),
                ('day_5', models.TextField(blank=True, null=True)),
                ('day_6', models.TextField(blank=True, null=True)),
                ('day_7', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='Packets.hotel')),
                ('packet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='Packets.category')),
            ],
        ),
        migrations.CreateModel(
            name='PacketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='media/packet_image/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('packet_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Packets.packet')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='media/hotel_image/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('hotel_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Packets.hotel')),
            ],
        ),
    ]
