# Generated by Django 4.1.7 on 2023-02-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
