# Generated by Django 4.1.7 on 2023-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='packet',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='packetimage',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='packetimage',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
