# Generated by Django 4.1.7 on 2023-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packets', '0002_alter_hotelimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/hotel/'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/hotel_image/'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='arrival',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='packet',
            name='availability',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='date_start',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='day_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='day_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='day_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='day_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='day_5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='day_6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='day_7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='departure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='packet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/packet/'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='in_stock',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='schedule',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='packetimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/packet_image/'),
        ),
    ]
