# Generated by Django 4.1.7 on 2023-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packets', '0003_alter_hotel_image_alter_hotelimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet',
            old_name='paket_category',
            new_name='packet_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='packetimage',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
