# Generated by Django 4.1.7 on 2023-02-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packets', '0003_alter_hotel_image_alter_packet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('BEACHES', 'beaches'), ('ICONIC CITIES', 'iconic cities'), ('DESERTS', 'deserts'), ('MOUNTAINS', 'mountains'), ('SKIING', 'skiing'), ('CAMPING', 'camping'), ('TROPIC', 'tropic')], max_length=200),
        ),
    ]
